//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Customers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Customers.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O complemento do endereço pode conter no máximo 20 caracteres..
        /// </summary>
        internal static string ADDRESS_COMPLEMENT_IS_TOO_LONG {
            get {
                return ResourceManager.GetString("ADDRESS_COMPLEMENT_IS_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O logradouro pode conter no máximo 50 caracteres..
        /// </summary>
        internal static string ADDRESS_IS_TOO_LONG {
            get {
                return ResourceManager.GetString("ADDRESS_IS_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número do logradouro pode conter no máximo 10 caracteres..
        /// </summary>
        internal static string ADDRESS_NUMBER_IS_TOO_LONG {
            get {
                return ResourceManager.GetString("ADDRESS_NUMBER_IS_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da cidade pode conter no máximo 30 caracteres..
        /// </summary>
        internal static string CITY_NAME_IS_TOO_LONG {
            get {
                return ResourceManager.GetString("CITY_NAME_IS_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail é obrigatório..
        /// </summary>
        internal static string EMAIL_IS_MANDATORY {
            get {
                return ResourceManager.GetString("EMAIL_IS_MANDATORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail não pode conter mais do que 40 caracteres..
        /// </summary>
        internal static string EMAIL_IS_TOO_LONG {
            get {
                return ResourceManager.GetString("EMAIL_IS_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número do logradouro é inválido..
        /// </summary>
        internal static string INVALID_ADDRESS_NUMBER {
            get {
                return ResourceManager.GetString("INVALID_ADDRESS_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código de área é inválido..
        /// </summary>
        internal static string INVALID_AREA_CODE {
            get {
                return ResourceManager.GetString("INVALID_AREA_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da cidade é inválido..
        /// </summary>
        internal static string INVALID_CITY_NAME {
            get {
                return ResourceManager.GetString("INVALID_CITY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail é inválido..
        /// </summary>
        internal static string INVALID_EMAIL {
            get {
                return ResourceManager.GetString("INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é inválido..
        /// </summary>
        internal static string INVALID_NAME {
            get {
                return ResourceManager.GetString("INVALID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número de telefone é inválido..
        /// </summary>
        internal static string INVALID_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("INVALID_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigla do estado inválida..
        /// </summary>
        internal static string INVALID_STATE_CODE {
            get {
                return ResourceManager.GetString("INVALID_STATE_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CEP é inválido..
        /// </summary>
        internal static string INVALID_ZIP_CODE {
            get {
                return ResourceManager.GetString("INVALID_ZIP_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é obrigatório..
        /// </summary>
        internal static string NAME_IS_MANDATORY {
            get {
                return ResourceManager.GetString("NAME_IS_MANDATORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome pode conter no máximo 20 caracteres..
        /// </summary>
        internal static string NAME_IS_TOO_LONG {
            get {
                return ResourceManager.GetString("NAME_IS_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número de telefone não pode conter mais do que 15 caracteres..
        /// </summary>
        internal static string PHONE_NUMBER_IS_TOO_LONG {
            get {
                return ResourceManager.GetString("PHONE_NUMBER_IS_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao tentar efetuar a criação de um novo cliente..
        /// </summary>
        internal static string UNEXPECTED_ERROR_WHILE_CREATING_CUSTOMER {
            get {
                return ResourceManager.GetString("UNEXPECTED_ERROR_WHILE_CREATING_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CEP pode conter no máximo 8 caracteres..
        /// </summary>
        internal static string ZIP_CODE_IS_TOO_LONG {
            get {
                return ResourceManager.GetString("ZIP_CODE_IS_TOO_LONG", resourceCulture);
            }
        }
    }
}
