// <auto-generated />
using System;
using Clientes.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Customers.Migrations
{
    [DbContext(typeof(ClientesDbContext))]
    [Migration("20190325090955_AddedSeedData")]
    partial class AddedSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Customers.Models.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CodigoArea");

                    b.Property<string>("Email")
                        .HasMaxLength(40);

                    b.Property<string>("Nome")
                        .HasMaxLength(20);

                    b.Property<string>("Telefone")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.ToTable("Cliente");

                    b.HasData(
                        new { Id = new Guid("d201f4ab-46e7-48b7-80d1-bfd5569f1316"), Email = "cliente1@email.com", Nome = "Cliente1" },
                        new { Id = new Guid("5ba32385-0894-4589-85d5-8c83f924711c"), CodigoArea = 41, Email = "cliente1@email2.com", Nome = "Cliente2", Telefone = "999999999" },
                        new { Id = new Guid("5cb5a9bc-6ae7-43ed-ac6f-0ca70376cc3c"), CodigoArea = 11, Email = "cliente1@email3.com", Nome = "Cliente3", Telefone = "888888888" },
                        new { Id = new Guid("b815c0a7-f0a6-4943-aa08-180a992e838e") },
                        new { Id = new Guid("3f1be2c4-b509-47a2-a097-93aef7d337b6") }
                    );
                });

            modelBuilder.Entity("Customers.Models.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CEP")
                        .HasMaxLength(8);

                    b.Property<string>("Cidade")
                        .HasMaxLength(30);

                    b.Property<Guid?>("ClienteForeignKey");

                    b.Property<string>("Complemento")
                        .HasMaxLength(20);

                    b.Property<string>("Logradouro")
                        .HasMaxLength(50);

                    b.Property<string>("Numero")
                        .HasMaxLength(10);

                    b.Property<string>("UF")
                        .HasMaxLength(2);

                    b.HasKey("Id");

                    b.HasIndex("ClienteForeignKey")
                        .IsUnique()
                        .HasFilter("[ClienteForeignKey] IS NOT NULL");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("Customers.Models.Endereco", b =>
                {
                    b.HasOne("Customers.Models.Cliente", "Cliente")
                        .WithOne("Endereco")
                        .HasForeignKey("Customers.Models.Endereco", "ClienteForeignKey");
                });
#pragma warning restore 612, 618
        }
    }
}
