// <auto-generated />
using System;
using Clientes.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Customers.Migrations
{
    [DbContext(typeof(ClientesDbContext))]
    [Migration("20190325023725_DbUpdate1")]
    partial class DbUpdate1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Customers.Models.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CodigoArea");

                    b.Property<string>("Email")
                        .HasMaxLength(40);

                    b.Property<string>("Nome")
                        .HasMaxLength(20);

                    b.Property<string>("Telefone")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Customers.Models.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CEP")
                        .HasMaxLength(8);

                    b.Property<string>("Cidade")
                        .HasMaxLength(30);

                    b.Property<Guid?>("ClienteForeignKey");

                    b.Property<string>("Complemento")
                        .HasMaxLength(20);

                    b.Property<string>("Logradouro")
                        .HasMaxLength(50);

                    b.Property<string>("Numero")
                        .HasMaxLength(10);

                    b.Property<string>("UF")
                        .HasMaxLength(2);

                    b.HasKey("Id");

                    b.HasIndex("ClienteForeignKey")
                        .IsUnique()
                        .HasFilter("[ClienteForeignKey] IS NOT NULL");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("Customers.Models.Endereco", b =>
                {
                    b.HasOne("Customers.Models.Cliente", "Cliente")
                        .WithOne("Endereco")
                        .HasForeignKey("Customers.Models.Endereco", "ClienteForeignKey");
                });
#pragma warning restore 612, 618
        }
    }
}
